### ISSUE TITLE
[1.5.2] Not finding unavailable items

### ISSUE THREAD

**Issue by doktorstick** [raiguard/Factorio-QuickItemSearch#1]
From [Factorio-SmallMods #9](https://github.com/raiguard/Factorio-SmallMods/issues/9)

Here's a [video](https://www.dropbox.com/s/vt3cz0169q5oomt/quick-no-items.mp4?dl=0) showing you that it does not find items if you are outside of a roboport range. It also shows (I think) that the correct settings are set.

**Comment by raiguard** [comment]
...huh. That's interesting. Could you please send me the save file?

**Comment by doktorstick** [comment]
[Save](https://www.dropbox.com/s/598lfoqpr7imdjy/bug-quick-items.zip?dl=0). I delineated the border where it works/fails. It works on the white tiles; it fails on the black. I was searching for "request".

**Comment by raiguard** [comment]
Oh... LOL. We both made a mistake.

You're changing the setting for Recipe Book instead of QIS. Enable unavailable items for QIS and it'll work fine! :D

**Comment by doktorstick** [comment]
Hah, what fail! I went and looked at the video and sure enough, I went to Recipe Book instead of QIS. /facepalm

> It also shows (I think) that the correct settings are set.

And it turns out, I don't think so good.

**Comment by raiguard** [comment]
The next update will let you set logistic requests for unavailable items as well. :D
