### ISSUE TITLE
Stack of preset filters

### ISSUE THREAD

**Issue by Retster** [raiguard/Factorio-QuickItemSearch#11]
It will be useful to have several preset filters for list of items for differerent situations. Also this list should be as simple to order from logistics network and similiar behawiator for put that list of items into trash-list . 

It can be panel in the search tab with stack of buttons and each button has interface similiar to constant combinator interface where we are will set our list of items.
klick - request stack of item
Klick+ shift - trash stack of items
Klick+ ctrl - set stack of items

Example i want to go smash bitters, i need granades landmines, turrets etc, its will be _war pack_ set. Or if i want to build chem setup i need pipes, chem plant refineris, pumps _chem pack_.

PS: thank your for mod, it's great qol!

**Comment by raiguard** [comment]
Hmm, I'll consider it. I eventually want to do a bit of redesigning on this mod because there are some other features I want to add as well. But, it won't be for a while, because I'll be getting busier IRL with a job search, and I need to do some updates to some of my other mods that I've been neglecting.

**Comment by Retster** [comment]
Sure, take your time, best luck and have fun!

**Comment by raiguard** [comment]
I've decided to not add this, as it feels like feature creep. I want to keep the mod relatively simple and focused. I'm sorry!

The functionality you're looking for is mostly provided by [Auto trash](https://mods.factorio.com/mod/AutoTrash).
