### ISSUE TITLE
There's a typo in 'shortcut.lua' that prevents the mod from loading.

### ISSUE THREAD

**Issue by curtwagner1984** [raiguard/Factorio-QuickItemSearch#12]
Instead of `local data_util = require("__flib__.data_util")` it says `local data_util = require("__flib__.data-util")` I changed it manually to the former and it seems to load and work just fine.

**Comment by raiguard** [comment]
This is not a typo. The filenames were changed to use snake-case to be consistent with the base game (`data-updates`, etc.). The old paths continue to work for now but will be removed when factorio 1.1 releases.

**Comment by raiguard** [comment]
Oh, didn't notice that this was on the QIS repository. The way to fix this is to update flib (the Factorio Library). I will update the dependency for the next version of QIS.
