### ISSUE TITLE
Quick-Trash-All not working?

### ISSUE THREAD

**Issue by power-5000** [raiguard/Factorio-QuickItemSearch#13]
#### Describe the Bug

The Quick-Trash-All feature only works on no requested items. I don't know if I understand the documentation wrong or something is broke. I press ctrl-shift-T to quick trash let say my belts and rails that I have 400 requested and auto trash at 1000 and I have 800. None for the belts are put in my trash slots however things I'm not requesting such as my space power armor are put in auto trash.

#### To Reproduce

1. Have Items in inventory that are above the requested amount and below the auto-trash amount. additionally have items that are not requested.
2. Press the quick-trash-all key and all of the first item will remain and items not requested will be put in auto trash.

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username
Username: power5000
Save: https://drive.google.com/file/d/1-OHX3mYwfOOQfVWNfWVCIJ_R-rTfg2OM/view?usp=sharing

Note: There are lots of mods but I did try it on a vanilla save as well.

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-QuickItemSearch/files/5413065/factorio-current.log)

**Comment by raiguard** [comment]
There is something strange going on here. Sometimes the `set_personal_logistic_request` function is failing where it shouldn't be. This affected temporary requests as well. I've added a workaround until the actual issue can be figured out. Thank you for the report!
