### ISSUE TITLE
Request/Trash amount not set correctly when using only the slider

### ISSUE THREAD

**Issue by Choumiko** [raiguard/Factorio-QuickItemSearch#14]
#### Describe the Bug

Setting the request/trash amounts only using the sliders leaves the values at default (stack size for request, inf. for trash)

#### To Reproduce

1. Press Ctrl + F
2. Search for any item
3. Press shift + enter
4. Change the request or trash amount only using the slider
5. Click Set temporary/persistent request
6. Check the character logistics tab. Values are not what was shown in the qis gui

#### Save file & Username
Choumiko
[qis_bug.zip](https://github.com/raiguard/Factorio-QuickItemSearch/files/5518453/qis_bug.zip)

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next release.
