### ISSUE TITLE
Logistic network items show as unavailable

### ISSUE THREAD

**Issue by UltraJohn** [raiguard/Factorio-QuickItemSearch#15]
#### Describe the Bug

Searching for items that are in the logistics network show as unavailable (red)

#### To Reproduce

1. Press Ctrl-F
2. Search for any item that is in the logistics network chests
3. Item shows up as unavailable (red)

**Comment by UltraJohn** [comment]
Fixed by re-enabling my personal logistics network in the menu, didn't realize it had turned off somehow.

**Comment by raiguard** [comment]
Yeah, sometimes that happens to me as well. It's annoying.
