### ISSUE TITLE
Reliable "crash"

### ISSUE THREAD

**Issue by NotRexButCaesar** [raiguard/Factorio-QuickItemSearch#16]
#### Describe the Bug

The mod Quick Item Search (2.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickItemSearch::qis-confirm (ID 237)
__QuickItemSearch__/scripts/gui/search.lua:366: attempt to index field 'results' (a nil value)
stack traceback:
	__QuickItemSearch__/scripts/gui/search.lua:366: in function 'select_item'
	__QuickItemSearch__/control.lua:73: in function <__QuickItemSearch__/control.lua:63>

#### To Reproduce

Press shift-f to open the menu
click to unfocus the search bar
press e

#### Save file & Username

Username: AmericanPatriot
Save: any newly created save, but here you go
[Demo.zip](https://github.com/raiguard/Factorio-QuickItemSearch/files/5999623/Demo.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-QuickItemSearch/files/5999628/factorio-current.log)

**Comment by raiguard** [comment]
Thank you, fixed for the next release.
