### ISSUE TITLE
Automatically close search window once item is selected or request is made

### ISSUE THREAD

**Issue by azaghal** [raiguard/Factorio-QuickItemSearch#17]
#### Is your feature request related to a problem? Please describe.

When picking an item or setting a logistics request using quick item search window, I find it frustrating that after such an action I need to explicitly close the quick item search window. In most cases I either want to be able to build with the selected item immediately, or to go on with my other business. In both cases the window will get in the way (occupying a big chunk of the screen).

#### Describe the solution you'd like

The quick item search window should close automatically once an item has been selected from the list, or once a logistics request has been set.

#### Additional context

This is explicitly related to new GUI introduced in version 2.0.x. I would assume that some people might find it helpful to keep the window open, but perhaps it would be better to make such behaviour configurable instead. For me Quick Item Search has always been kind of a one-off type of thing - just finding that one item I do not have in the quickbar, or that one item that I do not want to chase around in the inventory screen. Even in case of logistics requests, I have mostly used it for setting temporary requests (when you realise you are missing something specific for a build) - if I want to set-up multiple (permanent) requests, usually I opt for using the game's built-in GUI instead.

**Comment by raiguard** [comment]
I can add an option for this.

**Comment by saaadel** [comment]
please! +1 for this

**Comment by raiguard** [comment]
After altogether far too long, I've added this. Sorry for the wait!

**Comment by azaghal** [comment]
No worries - sometimes it's necessary to take break from games like Factorio :) Thanks for adding the feature!
