### ISSUE TITLE
Better visibility of selected item in the search list

### ISSUE THREAD

**Issue by azaghal** [raiguard/Factorio-QuickItemSearch#19]
#### Is your feature request related to a problem? Please describe.

When picking item from the search list, I find it hard to see what item is currently selected.

#### Describe the solution you'd like

If possible, it would be nice if the currently selected item would stand-out a bit more compared to the rest of the entries. This could be done by using bolder font, or changing the selected row's background colour.

#### Additional context

This is primarily related to GUI changes in the 2.0.0 version.

There are probably two separate things that affect visibility of selected item:

1. The search box itself is tinted yellow while still typing. Once you press "Enter", it switches to being grey, and the first item gets the yellow text colour. However, the search box colour change is way more dominant than the text colour change due to its size, and due to current eye focus (that is the place you are looking at at that point). So your eyes/brain probably focus more on a change in colour of the search box than the first selected item.

2. Throughout the rest of the game, the way to emphasize selected item (in inventory, quickbar, craft tab) is by changing background colour of entire button - not just the text colour. Current behaviour in Quick Item Search could be considered inconsistent from that perspective as well.

As an extra note, I think that when highlighting selected item, it would be useful to highlight the entire row instead of just the item name. I.e. both the item name and the quantity available. This should make it easier for users to locate available quantity of the item being selected.

Oh, and since I have created three issues in succession - please don't take it as some kind of harsh criticism, I actually like the new interface's decision to show item names more than the old one with just icons - sometimes you have an idea what you need to locate by name, but no idea what the icon is, especially with mods that add a lot of items :)

**Comment by raiguard** [comment]
Everything you have said in this issue is true, and is all stuff that I originally intended on doing. However, it is the way it is because of mod API limitations. It's literally impossible to make the entire row's background change color when hovered, that's just not something mods can do.

If this ever becomes possible in the future, then I will do it. But for now, we're stuck with the way it is. I can make the selected item stand out more with a bolder color or font, but I can't do anything with the background. Sorry!

**Comment by azaghal** [comment]
No worries, thanks for the explanation :)

Using bolder font would probably help, though - so if that is a possibility, perhaps that could be a nice and (hopefully) simple change.
