### ISSUE TITLE
Cannot join

### ISSUE THREAD

**Issue by kuxynator** [raiguard/Factorio-QuickItemSearch#21]
Cannot join. The following mod event handlers are not identical between you and the server. This indicates that the following mods are not multiplayer (save/load) safe. (See the log file for more details):

mod-QuickItemSearch

**Comment by raiguard** [comment]
Please post the log and save file...

**Comment by kuxynator** [comment]
same error again
[factorio-current.log](https://github.com/raiguard/Factorio-QuickItemSearch/files/6132203/factorio-current.log)
save file too big

**Comment by raiguard** [comment]
Please create a new world with the mod set, then upload that. I just need it so I can press sync mods with save.

**Comment by kuxynator** [comment]
same error again. here an new world saved game.
https://www.file-upload.net/download-14533926/QuickItemSearch.zip.html
delete file link: https://www.file-upload.net/delete-14533926/1xit67.html

**Comment by raiguard** [comment]
~~Ack, I waited too long to download it. Either that, or the website is just broken.~~

~~You can upload a new save file with the modset directly to GitHub, it should be small enough.~~

Turns out, I figured out the issue. I'll have it fixed for the next version.
