### ISSUE TITLE
control.lua:116: attempt to index local 'gui_data' (a nil value)

### ISSUE THREAD

**Issue by kuxynator** [raiguard/Factorio-QuickItemSearch#22]
The mod Quick Item Search (2.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickItemSearch::qis-nav-down (ID 339)
__QuickItemSearch__/control.lua:116: attempt to index local 'gui_data' (a nil value)
stack traceback:
	__QuickItemSearch__/control.lua:116: in function <__QuickItemSearch__/control.lua:112>
	
had installed a few new mods and loaded the game again. 
Surfaces Reloaded, Transport Drones

**Comment by raiguard** [comment]
Fixed for the next release.
