### ISSUE TITLE
Display all outstanding temporary requests

### ISSUE THREAD

**Issue by Dagothur** [raiguard/Factorio-QuickItemSearch#24]
#### Is your feature request related to a problem? Please describe.

If you set up a bunch of temporary requests it can be difficult to determine when they are all fulfilled.

#### Describe the solution you'd like

A mechanism to display all outstanding temporary requests. (e.g. a button, checkbox, hotkey or even typing a key word or trigger word into the search such as "showtemp")

#### Additional context

Nothing. Thanks for the great mod.

**Comment by raiguard** [comment]
Sourcehut ticket: https://todo.sr.ht/~raiguard/factorio-mods/10

**Comment by raiguard** [comment]
This mod is no longer receiving new features.
