### ISSUE TITLE
Crash on start up with other addon: Rocket Log

### ISSUE THREAD

**Issue by Bykow** [raiguard/Factorio-QuickItemSearch#28]
#### Describe the Bug

I had a running and working save with quick item search. I added another mod called Rocket Log (https://mods.factorio.com/mod/rocket-log) and after that Quick Item Search started to give these errors at startup (directly at load of save)

#### To Reproduce

1. Install Quick Item Search
2. Install Rockert Log
3. Launch the game

#### Save file & Username
Username: bykoow
File: https://www.swisstransfer.com/d/adb42c82-f482-4867-a3d1-afd7287a9ceb

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-QuickItemSearch/files/8594994/factorio-current.log)

#### Error 
https://cdn.discordapp.com/attachments/708269007098085448/969717826963267615/unknown.png

**Comment by raiguard** [comment]
Sourcehut ticket: https://todo.sr.ht/~raiguard/factorio-mods/11

**Comment by raiguard** [comment]
Was fixed in 44002cc.
