### ISSUE TITLE
Using tab to select the nav bar doesn't cancel selection

### ISSUE THREAD

**Issue by JanSharp** [raiguard/Factorio-QuickItemSearch#3]
To reproduce:
- create a new world
- open quick item search gui
- search for "a"
- shift enter to select something
- move away from the first button using arrow keys
- press tab going back to the nav bar
- shift enter again, and now there are 2 selections
- if 2 selections "overlap" it causes and error

making a pattern with multiple selections:
![image](https://user-images.githubusercontent.com/58273964/88087798-c1c39580-cb89-11ea-8267-55feee8e5eb2.png)

error caused by overlap:
![image](https://user-images.githubusercontent.com/58273964/88087613-790bdc80-cb89-11ea-874d-3fcc1dcd8ebe.png)

**Comment by JanSharp** [comment]
Curious, i don't know how to add the bug tag. I assume i can't add it then, only moderators or so. Or i'm very blind.

**Comment by JanSharp** [comment]
The essencially same issue also happens when in the request gui.
So another reproduction is:
- search for something
- shift enter x 2
- tab x 2
- enter

**Comment by raiguard** [comment]
Unfortunately there is no way to tell when tab is pressed when your inside a textfield, so there is no way for me to just straight-up prevent it, especially with multiplayer latency. So what I did instead was add logic to handle if the textfield confirmed or the text changes when it's not supposed to, so it can reset the state and prevent crashes.

Basically, just don't use tab. Use enter and escape instead. ;)

**Comment by JanSharp** [comment]
Yea, i figured it was because tab doesn't raise events (i think).
I'm just so used to using tab.

So that fix is what i expected.
