### ISSUE TITLE
Crash on click of arrow key

### ISSUE THREAD

**Issue by SGZ-Creations** [raiguard/Factorio-QuickItemSearch#33]
### Description

The mod Quick Item Search (2.1.8) caused a non-recoverable error.
Please report this error to the mod author.

```lua
Error while running event QuickItemSearch::qis-nav-up (ID 296)
__QuickItemSearch__/control.lua:104: attempt to index local 'gui_data' (a nil value)
stack traceback:
	__QuickItemSearch__/control.lua:104: in function <__QuickItemSearch__/control.lua:100>
```
### Reproduction

load save
arrow key up.
see error.

**Comment by raiguard** [comment]
Do you have a consistent reproduction for this? There is no save file attached to the issue.

**Comment by SGZ-Creations** [comment]
I had this happen every time have sadly forgotten the save it was on.

**Comment by SGZ-Creations** [comment]
tho should I find it again I will give u the save ASAP.

**Comment by raiguard** [comment]
Please let me know if you reproduce it again.
