### ISSUE TITLE
Quick Item Search 

### ISSUE THREAD

**Issue by 3vaLpwner** [raiguard/Factorio-QuickItemSearch#34]
### Description

Hello! Found a bug while was working on Debian 11, headless server 1.1.87.
Can not clearly understand what happened, there was a lot of players.

89844.791 Info GameActionHandler.cpp:5077: UpdateTick (5316516) processed PlayerJoinGame peerID(74) playerIndex(6) mode(connect) 
89848.149 Error MainLoop.cpp:1382: Exception at tick 5316716: The mod Quick Item Search (2.1.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickItemSearch::Custom event (ID 377)
Gui element with name qis_infinity_filter_window already present in the parent element.
stack traceback:
        [C]: in function 'add'
        __flib__/gui.lua:85: in function 'recursive_build'
        __flib__/gui.lua:150: in function 'build'
        __QuickItemSearch__/scripts/gui/infinity-filter.lua:14: in function 'build'
        __QuickItemSearch__/control.lua:145: in function <__QuickItemSearch__/control.lua:128>
        [C]: in function 'raise_event'
        __flib__/dictionary-lite.lua:329: in function <__flib__/dictionary-lite.lua:311>
stack traceback:
        [C]: in function 'raise_event'
        __flib__/dictionary-lite.lua:329: in function <__flib__/dictionary-lite.lua:311>
89848.149 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Quick Item Search (2.1.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickItemSearch::Custom event (ID 377)
Gui element with name qis_infinity_filter_window already present in the parent element.
stack traceback:
        [C]: in function 'add'
        __flib__/gui.lua:85: in function 'recursive_build'
        __flib__/gui.lua:150: in function 'build'
        __QuickItemSearch__/scripts/gui/infinity-filter.lua:14: in function 'build'
        __QuickItemSearch__/control.lua:145: in function <__QuickItemSearch__/control.lua:128>
        [C]: in function 'raise_event'
        __flib__/dictionary-lite.lua:329: in function <__flib__/dictionary-lite.lua:311>
stack traceback:
        [C]: in function 'raise_event'
        __flib__/dictionary-lite.lua:329: in function <__flib__/dictionary-lite.lua:311>"
89848.149 Info ServerMultiplayerManager.cpp:813: updateTick(5316716) changing state from(InGame) to(Failed)

**Comment by raiguard** [comment]
Do you have a consistent reproduction for this?
