### ISSUE TITLE
When changing mods of a saved game, quick item search reports an error

### ISSUE THREAD

**Issue by gisanka** [raiguard/Factorio-QuickItemSearch#38]
### Description

I changed my mod list on a save and after that quick item search reports this error. I'm aware that I'm doing something which is not supported and might break and just report it in case you are interested ;-)

Die Mod Quick Item Search (2.1.9) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event QuickItemSearch::Custom event (ID 336)
Gui element with name qis_search_window already present in the parent element.
stack traceback:
	[C]: in function 'add'
	__flib__/gui.lua:89: in function 'recursive_build'
	__flib__/gui.lua:154: in function 'build'
	__QuickItemSearch__/scripts/gui/search.lua:15: in function 'build'

	__QuickItemSearch__/control.lua:147: in function <__QuickItemSearch__/control.lua:128>
	[C]: in function 'raise_event'
	__flib__/dictionary-lite.lua:406: in function <__flib__/dictionary-lite.lua:354>
stack traceback:
	[C]: in function 'raise_event'
	__flib__/dictionary-lite.lua:406: in function <__flib__/dictionary-lite.lua:354>

[factorio-current.log](https://github.com/raiguard/QuickItemSearch/files/15235304/factorio-current.log)

### Reproduction

1. play the game
2. change mod list
3. try to load old save with new mod list

[quickitemsearch.zip](https://github.com/raiguard/QuickItemSearch/files/15235329/quickitemsearch.zip)

**Comment by Golllog** [comment]
Not changing mod list here, simple update of the Quick Search mod to QuickItemSearch_2.1.9 from 2.1.8.  My SE + K2 game throws a fatal error on loading the save.  I have about a zillon mods in my save, so appreciate there can be other factors, but a rollback to Quick Search 2.1.8 and the save loads normally.  

Thanks for the fantastic mods raidguard!  

Here's the error from the Factorio Log File, let me know if you need anything else.

[factorio-current.log](https://github.com/raiguard/QuickItemSearch/files/15242023/factorio-current.log)

```
  80.073 Error MainLoop.cpp:1404: Exception at tick 70584819: The mod Quick Item Search (2.1.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickItemSearch::Custom event (ID 526)
Gui element with name qis_search_window already present in the parent element.
stack traceback:
	[C]: in function 'add'
	__flib__/gui.lua:89: in function 'recursive_build'
	__flib__/gui.lua:154: in function 'build'
	__QuickItemSearch__/scripts/gui/search.lua:15: in function 'build'
	__QuickItemSearch__/control.lua:147: in function <__QuickItemSearch__/control.lua:128>
	[C]: in function 'raise_event'
	__flib__/dictionary-lite.lua:406: in function <__flib__/dictionary-lite.lua:354>
stack traceback:
	[C]: in function 'raise_event'
	__flib__/dictionary-lite.lua:406: in function <__flib__/dictionary-lite.lua:354>

```
