### ISSUE TITLE
"Cannot open Quick Item Search, dictionary translation has not yet finished."

### ISSUE THREAD

**Issue by 0xRainy** [raiguard/Factorio-QuickItemSearch#6]
Updated to version: 1.5.5
Been in game for an hour and still getting this message. Didn't have this issue on previous version and haven't added any new mods since.

**Comment by raiguard** [comment]
Could you please send me your save file?

**Comment by 0xRainy** [comment]
https://drive.google.com/file/d/1KDhtlgsOgaFQPxasyPyqRAL2LYI0km-e/view?usp=sharing
There is the save

**Comment by raiguard** [comment]
Thanks. Turns out it was a stupid mistake on my part, related to a fix I made in the most recent patch. It's fixed for the next version.

**Comment by raiguard** [comment]
The patch has been released.
