### ISSUE TITLE
ctrl-f with Universe Viewer (Space Exploration) open

### ISSUE THREAD

**Issue by TaylorVoth** [raiguard/Factorio-QuickItemSearch#7]
The mod Quick Item Search (1.5.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickItemSearch::qis-search (ID 227)
The mod Space Exploration (0.3.100) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_gui_opened (ID 84)
The mod Quick Item Search (1.5.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickItemSearch::on_gui_closed (ID 85)
__QuickItemSearch__/scripts/gui/qis.lua:87: attempt to index local 'gui_data' (a nil value)
stack traceback:
	__QuickItemSearch__/scripts/gui/qis.lua:87: in function 'handler'
	__flib__/gui.lua:385: in function 'dispatch_handlers'
	__flib__/gui.lua:171: in function <__flib__/gui.lua:171>
	[C]: in function '__newindex'
	__QuickItemSearch__/scripts/gui/qis.lua:319: in function 'create'
	__QuickItemSearch__/scripts/gui/qis.lua:340: in function 'toggle'
	__QuickItemSearch__/control.lua:105: in function <__QuickItemSearch__/control.lua:101>
stack traceback:
	__space-exploration__/scripts/zonelist.lua:1192: in function 'callback'
	__space-exploration__/scripts/event.lua:14: in function <__space-exploration__/scripts/event.lua:12>
stack traceback:
	[C]: in function '__newindex'
	__space-exploration__/scripts/zonelist.lua:1192: in function 'callback'
	__space-exploration__/scripts/event.lua:14: in function <__space-exploration__/scripts/event.lua:12>
stack traceback:
	__QuickItemSearch__/scripts/gui/qis.lua:319: in function 'create'
	__QuickItemSearch__/scripts/gui/qis.lua:340: in function 'toggle'
	__QuickItemSearch__/control.lua:105: in function <__QuickItemSearch__/control.lua:101>
stack traceback:
	[C]: in function '__newindex'
	__QuickItemSearch__/scripts/gui/qis.lua:319: in function 'create'
	__QuickItemSearch__/scripts/gui/qis.lua:340: in function 'toggle'
	__QuickItemSearch__/control.lua:105: in function <__QuickItemSearch__/control.lua:101>

Steps to recreate: Space Exploration mod post satellite launch to unlock Universe viewer (U)
hit Ctrl-f causes above error and crash to main menu.
Expected behaviour: simply select the search bar at the top of the screen and not asplode

**Comment by raiguard** [comment]
Thanks, this is fixed for the next version.

**Comment by raiguard** [comment]
Released the version four days ago, but forgot to close the issue.
