### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by zomb-676** [raiguard/Factorio-QuickItemSearch#8]
#### Describe the Bug

Server crashed but client is safe on multiplayer , while on single player,it just return to the main menu

#### To Reproduce

1.Hit Control+F and type all or part of the item I am looking for.
2.Hit Enter to confirm
3.Use Up Down Left Right to choose what I want
4. Then just as it is described in *Describe the Bug*

#### Save file & Username

save file: [_autosave3.zip](https://github.com/raiguard/Factorio-QuickItemSearch/files/5051201/_autosave3.zip)

userName: zomb_676

#### Log file

The key information:https://paste.ubuntu.com/p/SjZKscq3Pn/

The whole log file:https://paste.ubuntu.com/p/JCrZwGTd2p/

**Comment by raiguard** [comment]
One of the other mods you have installed is messing with my GUI, destroying the textfield. The textfield should never disappear like that. There's nothing I can do about badly designed mods messing with my logic. Sorry!

**Comment by raiguard** [comment]
I discovered the culprit: Advanced Combinator. That mod was deprecated yesterday and replaced with Improved Combinator, and the mod author has fixed the problem. Once that update is released, it should work!
