### ISSUE TITLE
Duplicate Item

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-QuickItemSearch#9]
#### Describe the Bug
I have the "Hovercrafts" mod (https://mods.factorio.com/mod/Hovercrafts) installed and when I search for it in your mod's GUI, some items appear to be duplicates. Show 2 Hovercrafts and 2 Missile Hovercrafts! The 4 appear in red, as I don't have them in my inventory.

#### To Reproduce

1. Open the game with Hovercrafts and QuickItemSearch installed.
2. Open QuickItemSearch GUI (Ctrl+F)
3. Search for "Hover"
4. See 4 items, 2 of each!

**Comment by Dominiquini** [comment]
The maintainer of the mod Hovercrafts has already fixed the problem!

Thank you.

**Comment by raiguard** [comment]
Ah, sorry, I totally forgot about this. I had suspected that it was Hovercrafts' fault but hadn't looked into it yet. Thanks for the report!
